const tickets=[{id:"TCK-1001",studentName:"Sample Student",studentId:"22140001",category:"Enrolment Issue",priority:"High",status:"Open",description:"Unable to enrol in a required professional experience unit due to a prerequisite issue.",createdDate:"2026-07-14"},{id:"TCK-1002",studentName:"Alex Chen",studentId:"22140002",category:"Rule Waiver",priority:"Medium",status:"In Progress",description:"Requesting a rule waiver because the required subject was not visible in the study plan.",createdDate:"2026-07-12"},{id:"TCK-1003",studentName:"Maya Singh",studentId:"22140003",category:"Technical Access",priority:"Low",status:"Resolved",description:"Could not access the degree progress dashboard. Issue resolved after browser cache refresh.",createdDate:"2026-07-10"}];
const ticketForm=document.getElementById("ticketForm"),ticketList=document.getElementById("ticketList"),statusFilter=document.getElementById("statusFilter"),categoryFilter=document.getElementById("categoryFilter"),toast=document.getElementById("toast"),exportBtn=document.getElementById("exportBtn");
function showToast(message){toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2300)}
function statusClass(status){return status.toLowerCase().replace(" ","-")}
function renderStats(){document.getElementById("totalTickets").textContent=tickets.length;document.getElementById("openTickets").textContent=tickets.filter(t=>t.status==="Open").length;document.getElementById("progressTickets").textContent=tickets.filter(t=>t.status==="In Progress").length;document.getElementById("resolvedTickets").textContent=tickets.filter(t=>t.status==="Resolved").length}
function getFilteredTickets(){const s=statusFilter.value,c=categoryFilter.value;return tickets.filter(t=>(s==="All"||t.status===s)&&(c==="All"||t.category===c))}
function renderTickets(){const filtered=getFilteredTickets();ticketList.innerHTML="";if(filtered.length===0){ticketList.innerHTML="<p class='helper-text'>No tickets match the selected filters.</p>";renderStats();return}filtered.forEach(ticket=>{const card=document.createElement("article");card.className="ticket-card";card.innerHTML=`<div class="ticket-card-top"><div><h3>${ticket.id} • ${ticket.category}</h3><div class="ticket-meta"><span class="pill ${ticket.priority.toLowerCase()}">${ticket.priority} Priority</span><span class="pill ${statusClass(ticket.status)}">${ticket.status}</span><span class="pill">${ticket.createdDate}</span></div></div><strong>${ticket.studentName}</strong></div><p class="ticket-description">${ticket.description}</p><p class="helper-text">Student ID: ${ticket.studentId}</p><div class="ticket-actions"><button class="secondary-btn" data-action="Open" data-id="${ticket.id}">Mark Open</button><button class="secondary-btn" data-action="In Progress" data-id="${ticket.id}">Mark In Progress</button><button class="secondary-btn" data-action="Resolved" data-id="${ticket.id}">Resolve</button></div>`;ticketList.appendChild(card)});renderStats()}
function createTicketId(){return `TCK-${1000+tickets.length+1}`}
ticketForm.addEventListener("submit",event=>{event.preventDefault();const newTicket={id:createTicketId(),studentName:document.getElementById("studentName").value.trim(),studentId:document.getElementById("studentId").value.trim(),category:document.getElementById("category").value,priority:document.getElementById("priority").value,status:"Open",description:document.getElementById("description").value.trim(),createdDate:new Date().toISOString().slice(0,10)};tickets.unshift(newTicket);ticketForm.reset();statusFilter.value="All";categoryFilter.value="All";renderTickets();showToast("New support ticket created")});
ticketList.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;const ticket=tickets.find(item=>item.id===button.dataset.id);if(ticket){ticket.status=button.dataset.action;renderTickets();showToast(`${ticket.id} updated to ${ticket.status}`)}});
statusFilter.addEventListener("change",renderTickets);categoryFilter.addEventListener("change",renderTickets);
exportBtn.addEventListener("click",()=>{const data=JSON.stringify(tickets,null,2),blob=new Blob([data],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="student-support-tickets.json";link.click();URL.revokeObjectURL(url);showToast("Sample tickets exported")});
renderTickets();
